export type Provincia = { codice: string; nome: string; regione: string };
export type IstatComune = { nome: string; provincia: string };

export const PROVINCE: Provincia[] = [
  { codice: "AG", nome: "Agrigento", regione: "Sicilia" },
  { codice: "AL", nome: "Alessandria", regione: "Piemonte" },
  { codice: "AN", nome: "Ancona", regione: "Marche" },
  { codice: "AO", nome: "Aosta", regione: "Valle d'Aosta" },
  { codice: "AP", nome: "Ascoli Piceno", regione: "Marche" },
  { codice: "AQ", nome: "L'Aquila", regione: "Abruzzo" },
  { codice: "AR", nome: "Arezzo", regione: "Toscana" },
  { codice: "AT", nome: "Asti", regione: "Piemonte" },
  { codice: "AV", nome: "Avellino", regione: "Campania" },
  { codice: "BA", nome: "Bari", regione: "Puglia" },
  { codice: "BAT", nome: "Barletta-Andria-Trani", regione: "Puglia" },
  { codice: "BG", nome: "Bergamo", regione: "Lombardia" },
  { codice: "BI", nome: "Biella", regione: "Piemonte" },
  { codice: "BL", nome: "Belluno", regione: "Veneto" },
  { codice: "BN", nome: "Benevento", regione: "Campania" },
  { codice: "BO", nome: "Bologna", regione: "Emilia-Romagna" },
  { codice: "BR", nome: "Brindisi", regione: "Puglia" },
  { codice: "BS", nome: "Brescia", regione: "Lombardia" },
  { codice: "BZ", nome: "Bolzano", regione: "Trentino-Alto Adige" },
  { codice: "CA", nome: "Cagliari", regione: "Sardegna" },
  { codice: "CB", nome: "Campobasso", regione: "Molise" },
  { codice: "CE", nome: "Caserta", regione: "Campania" },
  { codice: "CH", nome: "Chieti", regione: "Abruzzo" },
  { codice: "CL", nome: "Caltanissetta", regione: "Sicilia" },
  { codice: "CN", nome: "Cuneo", regione: "Piemonte" },
  { codice: "CO", nome: "Como", regione: "Lombardia" },
  { codice: "CR", nome: "Cremona", regione: "Lombardia" },
  { codice: "CS", nome: "Cosenza", regione: "Calabria" },
  { codice: "CT", nome: "Catania", regione: "Sicilia" },
  { codice: "CZ", nome: "Catanzaro", regione: "Calabria" },
  { codice: "EN", nome: "Enna", regione: "Sicilia" },
  { codice: "FC", nome: "Forlì-Cesena", regione: "Emilia-Romagna" },
  { codice: "FE", nome: "Ferrara", regione: "Emilia-Romagna" },
  { codice: "FG", nome: "Foggia", regione: "Puglia" },
  { codice: "FI", nome: "Firenze", regione: "Toscana" },
  { codice: "FM", nome: "Fermo", regione: "Marche" },
  { codice: "FR", nome: "Frosinone", regione: "Lazio" },
  { codice: "GE", nome: "Genova", regione: "Liguria" },
  { codice: "GO", nome: "Gorizia", regione: "Friuli-Venezia Giulia" },
  { codice: "GR", nome: "Grosseto", regione: "Toscana" },
  { codice: "IM", nome: "Imperia", regione: "Liguria" },
  { codice: "IS", nome: "Isernia", regione: "Molise" },
  { codice: "KR", nome: "Crotone", regione: "Calabria" },
  { codice: "LC", nome: "Lecco", regione: "Lombardia" },
  { codice: "LE", nome: "Lecce", regione: "Puglia" },
  { codice: "LI", nome: "Livorno", regione: "Toscana" },
  { codice: "LO", nome: "Lodi", regione: "Lombardia" },
  { codice: "LT", nome: "Latina", regione: "Lazio" },
  { codice: "LU", nome: "Lucca", regione: "Toscana" },
  { codice: "MB", nome: "Monza e Brianza", regione: "Lombardia" },
  { codice: "MC", nome: "Macerata", regione: "Marche" },
  { codice: "ME", nome: "Messina", regione: "Sicilia" },
  { codice: "MI", nome: "Milano", regione: "Lombardia" },
  { codice: "MN", nome: "Mantova", regione: "Lombardia" },
  { codice: "MO", nome: "Modena", regione: "Emilia-Romagna" },
  { codice: "MS", nome: "Massa-Carrara", regione: "Toscana" },
  { codice: "MT", nome: "Matera", regione: "Basilicata" },
  { codice: "NA", nome: "Napoli", regione: "Campania" },
  { codice: "NO", nome: "Novara", regione: "Piemonte" },
  { codice: "NU", nome: "Nuoro", regione: "Sardegna" },
  { codice: "OR", nome: "Oristano", regione: "Sardegna" },
  { codice: "PA", nome: "Palermo", regione: "Sicilia" },
  { codice: "PC", nome: "Piacenza", regione: "Emilia-Romagna" },
  { codice: "PD", nome: "Padova", regione: "Veneto" },
  { codice: "PE", nome: "Pescara", regione: "Abruzzo" },
  { codice: "PG", nome: "Perugia", regione: "Umbria" },
  { codice: "PI", nome: "Pisa", regione: "Toscana" },
  { codice: "PO", nome: "Prato", regione: "Toscana" },
  { codice: "PR", nome: "Parma", regione: "Emilia-Romagna" },
  { codice: "PT", nome: "Pistoia", regione: "Toscana" },
  { codice: "PU", nome: "Pesaro e Urbino", regione: "Marche" },
  { codice: "PV", nome: "Pavia", regione: "Lombardia" },
  { codice: "PZ", nome: "Potenza", regione: "Basilicata" },
  { codice: "RA", nome: "Ravenna", regione: "Emilia-Romagna" },
  { codice: "RC", nome: "Reggio Calabria", regione: "Calabria" },
  { codice: "RE", nome: "Reggio Emilia", regione: "Emilia-Romagna" },
  { codice: "RG", nome: "Ragusa", regione: "Sicilia" },
  { codice: "RI", nome: "Rieti", regione: "Lazio" },
  { codice: "RM", nome: "Roma", regione: "Lazio" },
  { codice: "RN", nome: "Rimini", regione: "Emilia-Romagna" },
  { codice: "RO", nome: "Rovigo", regione: "Veneto" },
  { codice: "SA", nome: "Salerno", regione: "Campania" },
  { codice: "SI", nome: "Siena", regione: "Toscana" },
  { codice: "SO", nome: "Sondrio", regione: "Lombardia" },
  { codice: "SP", nome: "La Spezia", regione: "Liguria" },
  { codice: "SR", nome: "Siracusa", regione: "Sicilia" },
  { codice: "SS", nome: "Sassari", regione: "Sardegna" },
  { codice: "SU", nome: "Sud Sardegna", regione: "Sardegna" },
  { codice: "SV", nome: "Savona", regione: "Liguria" },
  { codice: "TA", nome: "Taranto", regione: "Puglia" },
  { codice: "TE", nome: "Teramo", regione: "Abruzzo" },
  { codice: "TN", nome: "Trento", regione: "Trentino-Alto Adige" },
  { codice: "TO", nome: "Torino", regione: "Piemonte" },
  { codice: "TP", nome: "Trapani", regione: "Sicilia" },
  { codice: "TR", nome: "Terni", regione: "Umbria" },
  { codice: "TS", nome: "Trieste", regione: "Friuli-Venezia Giulia" },
  { codice: "TV", nome: "Treviso", regione: "Veneto" },
  { codice: "UD", nome: "Udine", regione: "Friuli-Venezia Giulia" },
  { codice: "VA", nome: "Varese", regione: "Lombardia" },
  { codice: "VB", nome: "Verbano-Cusio-Ossola", regione: "Piemonte" },
  { codice: "VC", nome: "Vercelli", regione: "Piemonte" },
  { codice: "VE", nome: "Venezia", regione: "Veneto" },
  { codice: "VI", nome: "Vicenza", regione: "Veneto" },
  { codice: "VR", nome: "Verona", regione: "Veneto" },
  { codice: "VT", nome: "Viterbo", regione: "Lazio" },
  { codice: "VV", nome: "Vibo Valentia", regione: "Calabria" },
];

export const COMUNI: IstatComune[] = [
  // AG - Agrigento
  { nome: "Agrigento", provincia: "AG" },
  { nome: "Sciacca", provincia: "AG" },
  { nome: "Licata", provincia: "AG" },
  { nome: "Canicattì", provincia: "AG" },
  { nome: "Porto Empedocle", provincia: "AG" },
  // AL - Alessandria
  { nome: "Alessandria", provincia: "AL" },
  { nome: "Tortona", provincia: "AL" },
  { nome: "Novi Ligure", provincia: "AL" },
  { nome: "Casale Monferrato", provincia: "AL" },
  { nome: "Acqui Terme", provincia: "AL" },
  // AN - Ancona
  { nome: "Ancona", provincia: "AN" },
  { nome: "Senigallia", provincia: "AN" },
  { nome: "Jesi", provincia: "AN" },
  { nome: "Fabriano", provincia: "AN" },
  { nome: "Osimo", provincia: "AN" },
  // AO - Aosta
  { nome: "Aosta", provincia: "AO" },
  { nome: "Châtillon", provincia: "AO" },
  { nome: "Saint-Vincent", provincia: "AO" },
  { nome: "Courmayeur", provincia: "AO" },
  // AP - Ascoli Piceno
  { nome: "Ascoli Piceno", provincia: "AP" },
  { nome: "San Benedetto del Tronto", provincia: "AP" },
  { nome: "Monteprandone", provincia: "AP" },
  { nome: "Grottammare", provincia: "AP" },
  // AQ - L'Aquila
  { nome: "L'Aquila", provincia: "AQ" },
  { nome: "Avezzano", provincia: "AQ" },
  { nome: "Sulmona", provincia: "AQ" },
  { nome: "Castel di Sangro", provincia: "AQ" },
  { nome: "Tagliacozzo", provincia: "AQ" },
  // AR - Arezzo
  { nome: "Arezzo", provincia: "AR" },
  { nome: "Cortona", provincia: "AR" },
  { nome: "Sansepolcro", provincia: "AR" },
  { nome: "Castiglion Fiorentino", provincia: "AR" },
  { nome: "Poppi", provincia: "AR" },
  { nome: "Bibbiena", provincia: "AR" },
  { nome: "Monte San Savino", provincia: "AR" },
  { nome: "Civitella in Val di Chiana", provincia: "AR" },
  // AT - Asti
  { nome: "Asti", provincia: "AT" },
  { nome: "Canelli", provincia: "AT" },
  { nome: "Nizza Monferrato", provincia: "AT" },
  { nome: "Costigliole d'Asti", provincia: "AT" },
  { nome: "Villanova d'Asti", provincia: "AT" },
  // AV - Avellino
  { nome: "Avellino", provincia: "AV" },
  { nome: "Ariano Irpino", provincia: "AV" },
  { nome: "Montoro", provincia: "AV" },
  { nome: "Cervinara", provincia: "AV" },
  // BA - Bari
  { nome: "Bari", provincia: "BA" },
  { nome: "Altamura", provincia: "BA" },
  { nome: "Mola di Bari", provincia: "BA" },
  { nome: "Bitonto", provincia: "BA" },
  { nome: "Ruvo di Puglia", provincia: "BA" },
  { nome: "Gravina in Puglia", provincia: "BA" },
  // BAT - Barletta-Andria-Trani
  { nome: "Barletta", provincia: "BAT" },
  { nome: "Andria", provincia: "BAT" },
  { nome: "Trani", provincia: "BAT" },
  { nome: "Canosa di Puglia", provincia: "BAT" },
  { nome: "Margherita di Savoia", provincia: "BAT" },
  // BG - Bergamo
  { nome: "Bergamo", provincia: "BG" },
  { nome: "Treviglio", provincia: "BG" },
  { nome: "Seriate", provincia: "BG" },
  { nome: "Dalmine", provincia: "BG" },
  { nome: "Romano di Lombardia", provincia: "BG" },
  // BI - Biella
  { nome: "Biella", provincia: "BI" },
  { nome: "Cossato", provincia: "BI" },
  { nome: "Gaglianico", provincia: "BI" },
  // BL - Belluno
  { nome: "Belluno", provincia: "BL" },
  { nome: "Feltre", provincia: "BL" },
  { nome: "Cortina d'Ampezzo", provincia: "BL" },
  { nome: "Agordo", provincia: "BL" },
  // BN - Benevento
  { nome: "Benevento", provincia: "BN" },
  { nome: "Montesarchio", provincia: "BN" },
  { nome: "Sant'Agata de' Goti", provincia: "BN" },
  // BO - Bologna
  { nome: "Bologna", provincia: "BO" },
  { nome: "Imola", provincia: "BO" },
  { nome: "Casalecchio di Reno", provincia: "BO" },
  { nome: "San Lazzaro di Savena", provincia: "BO" },
  { nome: "Borgo Panigale", provincia: "BO" },
  // BR - Brindisi
  { nome: "Brindisi", provincia: "BR" },
  { nome: "Fasano", provincia: "BR" },
  { nome: "Francavilla Fontana", provincia: "BR" },
  { nome: "Ostuni", provincia: "BR" },
  { nome: "Mesagne", provincia: "BR" },
  // BS - Brescia
  { nome: "Brescia", provincia: "BS" },
  { nome: "Desenzano del Garda", provincia: "BS" },
  { nome: "Chiari", provincia: "BS" },
  { nome: "Gardone Val Trompia", provincia: "BS" },
  { nome: "Sirmione", provincia: "BS" },
  // BZ - Bolzano
  { nome: "Bolzano", provincia: "BZ" },
  { nome: "Merano", provincia: "BZ" },
  { nome: "Bressanone", provincia: "BZ" },
  { nome: "Vipiteno", provincia: "BZ" },
  { nome: "Brunico", provincia: "BZ" },
  // CA - Cagliari
  { nome: "Cagliari", provincia: "CA" },
  { nome: "Quartu Sant'Elena", provincia: "CA" },
  { nome: "Selargius", provincia: "CA" },
  { nome: "Assemini", provincia: "CA" },
  // CB - Campobasso
  { nome: "Campobasso", provincia: "CB" },
  { nome: "Termoli", provincia: "CB" },
  { nome: "Bojano", provincia: "CB" },
  { nome: "Larino", provincia: "CB" },
  // CE - Caserta
  { nome: "Caserta", provincia: "CE" },
  { nome: "Aversa", provincia: "CE" },
  { nome: "Marcianise", provincia: "CE" },
  { nome: "Maddaloni", provincia: "CE" },
  { nome: "Capua", provincia: "CE" },
  // CH - Chieti
  { nome: "Chieti", provincia: "CH" },
  { nome: "Lanciano", provincia: "CH" },
  { nome: "Vasto", provincia: "CH" },
  { nome: "Ortona", provincia: "CH" },
  // CL - Caltanissetta
  { nome: "Caltanissetta", provincia: "CL" },
  { nome: "Gela", provincia: "CL" },
  { nome: "Niscemi", provincia: "CL" },
  { nome: "Mussomeli", provincia: "CL" },
  // CN - Cuneo
  { nome: "Cuneo", provincia: "CN" },
  { nome: "Alba", provincia: "CN" },
  { nome: "Bra", provincia: "CN" },
  { nome: "Barolo", provincia: "CN" },
  { nome: "Mondovì", provincia: "CN" },
  { nome: "Saluzzo", provincia: "CN" },
  { nome: "Dogliani", provincia: "CN" },
  { nome: "Fossano", provincia: "CN" },
  { nome: "Busca", provincia: "CN" },
  // CO - Como
  { nome: "Como", provincia: "CO" },
  { nome: "Cantù", provincia: "CO" },
  { nome: "Erba", provincia: "CO" },
  { nome: "Cermenate", provincia: "CO" },
  { nome: "Mariano Comense", provincia: "CO" },
  // CR - Cremona
  { nome: "Cremona", provincia: "CR" },
  { nome: "Crema", provincia: "CR" },
  { nome: "Casalmaggiore", provincia: "CR" },
  { nome: "Soresina", provincia: "CR" },
  // CS - Cosenza
  { nome: "Cosenza", provincia: "CS" },
  { nome: "Rende", provincia: "CS" },
  { nome: "Rossano", provincia: "CS" },
  { nome: "Paola", provincia: "CS" },
  { nome: "Castrovillari", provincia: "CS" },
  // CT - Catania
  { nome: "Catania", provincia: "CT" },
  { nome: "Acireale", provincia: "CT" },
  { nome: "Misterbianco", provincia: "CT" },
  { nome: "Paternò", provincia: "CT" },
  { nome: "Giarre", provincia: "CT" },
  // CZ - Catanzaro
  { nome: "Catanzaro", provincia: "CZ" },
  { nome: "Lamezia Terme", provincia: "CZ" },
  { nome: "Soverato", provincia: "CZ" },
  { nome: "Chiaravalle Centrale", provincia: "CZ" },
  // EN - Enna
  { nome: "Enna", provincia: "EN" },
  { nome: "Piazza Armerina", provincia: "EN" },
  { nome: "Nicosia", provincia: "EN" },
  { nome: "Leonforte", provincia: "EN" },
  // FC - Forlì-Cesena
  { nome: "Forlì", provincia: "FC" },
  { nome: "Cesena", provincia: "FC" },
  { nome: "Cesenatico", provincia: "FC" },
  { nome: "Savignano sul Rubicone", provincia: "FC" },
  // FE - Ferrara
  { nome: "Ferrara", provincia: "FE" },
  { nome: "Cento", provincia: "FE" },
  { nome: "Comacchio", provincia: "FE" },
  { nome: "Argenta", provincia: "FE" },
  // FG - Foggia
  { nome: "Foggia", provincia: "FG" },
  { nome: "Cerignola", provincia: "FG" },
  { nome: "Manfredonia", provincia: "FG" },
  { nome: "San Severo", provincia: "FG" },
  { nome: "Lucera", provincia: "FG" },
  // FI - Firenze
  { nome: "Firenze", provincia: "FI" },
  { nome: "Greve in Chianti", provincia: "FI" },
  { nome: "Fiesole", provincia: "FI" },
  { nome: "Impruneta", provincia: "FI" },
  { nome: "Certaldo", provincia: "FI" },
  { nome: "Barberino Tavarnelle", provincia: "FI" },
  { nome: "Figline e Incisa Valdarno", provincia: "FI" },
  { nome: "Borgo San Lorenzo", provincia: "FI" },
  { nome: "Pontassieve", provincia: "FI" },
  // FM - Fermo
  { nome: "Fermo", provincia: "FM" },
  { nome: "Porto San Giorgio", provincia: "FM" },
  { nome: "Porto Sant'Elpidio", provincia: "FM" },
  { nome: "Montegiorgio", provincia: "FM" },
  // FR - Frosinone
  { nome: "Frosinone", provincia: "FR" },
  { nome: "Cassino", provincia: "FR" },
  { nome: "Alatri", provincia: "FR" },
  { nome: "Anagni", provincia: "FR" },
  { nome: "Sora", provincia: "FR" },
  // GE - Genova
  { nome: "Genova", provincia: "GE" },
  { nome: "Rapallo", provincia: "GE" },
  { nome: "Chiavari", provincia: "GE" },
  { nome: "Arenzano", provincia: "GE" },
  // GO - Gorizia
  { nome: "Gorizia", provincia: "GO" },
  { nome: "Monfalcone", provincia: "GO" },
  { nome: "Gradisca d'Isonzo", provincia: "GO" },
  // GR - Grosseto
  { nome: "Grosseto", provincia: "GR" },
  { nome: "Orbetello", provincia: "GR" },
  { nome: "Pitigliano", provincia: "GR" },
  { nome: "Sorano", provincia: "GR" },
  { nome: "Scansano", provincia: "GR" },
  { nome: "Capalbio", provincia: "GR" },
  { nome: "Manciano", provincia: "GR" },
  { nome: "Castiglione della Pescaia", provincia: "GR" },
  { nome: "Massa Marittima", provincia: "GR" },
  { nome: "Porto Santo Stefano", provincia: "GR" },
  { nome: "Follonica", provincia: "GR" },
  { nome: "Roccastrada", provincia: "GR" },
  // IM - Imperia
  { nome: "Imperia", provincia: "IM" },
  { nome: "Sanremo", provincia: "IM" },
  { nome: "Ventimiglia", provincia: "IM" },
  { nome: "Bordighera", provincia: "IM" },
  // IS - Isernia
  { nome: "Isernia", provincia: "IS" },
  { nome: "Venafro", provincia: "IS" },
  { nome: "Agnone", provincia: "IS" },
  // KR - Crotone
  { nome: "Crotone", provincia: "KR" },
  { nome: "Cirò Marina", provincia: "KR" },
  { nome: "Isola di Capo Rizzuto", provincia: "KR" },
  // LC - Lecco
  { nome: "Lecco", provincia: "LC" },
  { nome: "Merate", provincia: "LC" },
  { nome: "Calolziocorte", provincia: "LC" },
  // LE - Lecce
  { nome: "Lecce", provincia: "LE" },
  { nome: "Gallipoli", provincia: "LE" },
  { nome: "Nardò", provincia: "LE" },
  { nome: "Galatina", provincia: "LE" },
  { nome: "Copertino", provincia: "LE" },
  // LI - Livorno
  { nome: "Livorno", provincia: "LI" },
  { nome: "Piombino", provincia: "LI" },
  { nome: "Cecina", provincia: "LI" },
  { nome: "Portoferraio", provincia: "LI" },
  { nome: "Rosignano Marittimo", provincia: "LI" },
  // LO - Lodi
  { nome: "Lodi", provincia: "LO" },
  { nome: "Codogno", provincia: "LO" },
  { nome: "Casalpusterlengo", provincia: "LO" },
  // LT - Latina
  { nome: "Latina", provincia: "LT" },
  { nome: "Aprilia", provincia: "LT" },
  { nome: "Terracina", provincia: "LT" },
  { nome: "Fondi", provincia: "LT" },
  { nome: "Formia", provincia: "LT" },
  // LU - Lucca
  { nome: "Lucca", provincia: "LU" },
  { nome: "Viareggio", provincia: "LU" },
  { nome: "Capannori", provincia: "LU" },
  { nome: "Pietrasanta", provincia: "LU" },
  { nome: "Altopascio", provincia: "LU" },
  // MB - Monza e Brianza
  { nome: "Monza", provincia: "MB" },
  { nome: "Desio", provincia: "MB" },
  { nome: "Seregno", provincia: "MB" },
  { nome: "Sesto San Giovanni", provincia: "MB" },
  // MC - Macerata
  { nome: "Macerata", provincia: "MC" },
  { nome: "Civitanova Marche", provincia: "MC" },
  { nome: "Porto Recanati", provincia: "MC" },
  { nome: "Tolentino", provincia: "MC" },
  // ME - Messina
  { nome: "Messina", provincia: "ME" },
  { nome: "Barcellona Pozzo di Gotto", provincia: "ME" },
  { nome: "Milazzo", provincia: "ME" },
  { nome: "Patti", provincia: "ME" },
  // MI - Milano
  { nome: "Milano", provincia: "MI" },
  { nome: "Sesto San Giovanni", provincia: "MI" },
  { nome: "Cinisello Balsamo", provincia: "MI" },
  { nome: "Legnano", provincia: "MI" },
  { nome: "Rho", provincia: "MI" },
  // MN - Mantova
  { nome: "Mantova", provincia: "MN" },
  { nome: "Guidizzolo", provincia: "MN" },
  { nome: "Castiglione delle Stiviere", provincia: "MN" },
  { nome: "Viadana", provincia: "MN" },
  // MO - Modena
  { nome: "Modena", provincia: "MO" },
  { nome: "Carpi", provincia: "MO" },
  { nome: "Sassuolo", provincia: "MO" },
  { nome: "Formigine", provincia: "MO" },
  { nome: "Maranello", provincia: "MO" },
  // MS - Massa-Carrara
  { nome: "Massa", provincia: "MS" },
  { nome: "Carrara", provincia: "MS" },
  { nome: "Pontremoli", provincia: "MS" },
  { nome: "Aulla", provincia: "MS" },
  // MT - Matera
  { nome: "Matera", provincia: "MT" },
  { nome: "Montescaglioso", provincia: "MT" },
  { nome: "Policoro", provincia: "MT" },
  { nome: "Tursi", provincia: "MT" },
  { nome: "Pisticci", provincia: "MT" },
  { nome: "Bernalda", provincia: "MT" },
  { nome: "Nova Siri", provincia: "MT" },
  // NA - Napoli
  { nome: "Napoli", provincia: "NA" },
  { nome: "Giugliano in Campania", provincia: "NA" },
  { nome: "Torre del Greco", provincia: "NA" },
  { nome: "Pozzuoli", provincia: "NA" },
  { nome: "Casoria", provincia: "NA" },
  // NO - Novara
  { nome: "Novara", provincia: "NO" },
  { nome: "Borgomanero", provincia: "NO" },
  { nome: "Arona", provincia: "NO" },
  { nome: "Galliate", provincia: "NO" },
  // NU - Nuoro
  { nome: "Nuoro", provincia: "NU" },
  { nome: "Siniscola", provincia: "NU" },
  { nome: "Orosei", provincia: "NU" },
  { nome: "Dorgali", provincia: "NU" },
  // OR - Oristano
  { nome: "Oristano", provincia: "OR" },
  { nome: "Cabras", provincia: "OR" },
  { nome: "Ghilarza", provincia: "OR" },
  // PA - Palermo
  { nome: "Palermo", provincia: "PA" },
  { nome: "Bagheria", provincia: "PA" },
  { nome: "Monreale", provincia: "PA" },
  { nome: "Cefalù", provincia: "PA" },
  { nome: "Partinico", provincia: "PA" },
  // PC - Piacenza
  { nome: "Piacenza", provincia: "PC" },
  { nome: "Fiorenzuola d'Arda", provincia: "PC" },
  { nome: "Castel San Giovanni", provincia: "PC" },
  // PD - Padova
  { nome: "Padova", provincia: "PD" },
  { nome: "Abano Terme", provincia: "PD" },
  { nome: "Cittadella", provincia: "PD" },
  { nome: "Montagnana", provincia: "PD" },
  { nome: "Este", provincia: "PD" },
  // PE - Pescara
  { nome: "Pescara", provincia: "PE" },
  { nome: "Montesilvano", provincia: "PE" },
  { nome: "Spoltore", provincia: "PE" },
  { nome: "Penne", provincia: "PE" },
  // PG - Perugia
  { nome: "Perugia", provincia: "PG" },
  { nome: "Assisi", provincia: "PG" },
  { nome: "Gubbio", provincia: "PG" },
  { nome: "Città di Castello", provincia: "PG" },
  { nome: "Spoleto", provincia: "PG" },
  { nome: "Todi", provincia: "PG" },
  { nome: "Umbertide", provincia: "PG" },
  { nome: "Norcia", provincia: "PG" },
  { nome: "Trevi", provincia: "PG" },
  { nome: "Foligno", provincia: "PG" },
  { nome: "Castiglione del Lago", provincia: "PG" },
  { nome: "Deruta", provincia: "PG" },
  // PI - Pisa
  { nome: "Pisa", provincia: "PI" },
  { nome: "Pontedera", provincia: "PI" },
  { nome: "Cascina", provincia: "PI" },
  { nome: "San Miniato", provincia: "PI" },
  { nome: "Volterra", provincia: "PI" },
  // PO - Prato
  { nome: "Prato", provincia: "PO" },
  { nome: "Montemurlo", provincia: "PO" },
  { nome: "Poggio a Caiano", provincia: "PO" },
  // PR - Parma
  { nome: "Parma", provincia: "PR" },
  { nome: "Fidenza", provincia: "PR" },
  { nome: "Salsomaggiore Terme", provincia: "PR" },
  { nome: "Langhirano", provincia: "PR" },
  // PT - Pistoia
  { nome: "Pistoia", provincia: "PT" },
  { nome: "Montecatini-Terme", provincia: "PT" },
  { nome: "Monsummano Terme", provincia: "PT" },
  { nome: "Pescia", provincia: "PT" },
  // PU - Pesaro e Urbino
  { nome: "Pesaro", provincia: "PU" },
  { nome: "Urbino", provincia: "PU" },
  { nome: "Fano", provincia: "PU" },
  { nome: "Senigallia", provincia: "PU" },
  { nome: "Fossombrone", provincia: "PU" },
  // PV - Pavia
  { nome: "Pavia", provincia: "PV" },
  { nome: "Vigevano", provincia: "PV" },
  { nome: "Voghera", provincia: "PV" },
  { nome: "Mortara", provincia: "PV" },
  // PZ - Potenza
  { nome: "Potenza", provincia: "PZ" },
  { nome: "Melfi", provincia: "PZ" },
  { nome: "Maratea", provincia: "PZ" },
  { nome: "Lauria", provincia: "PZ" },
  { nome: "Rionero in Vulture", provincia: "PZ" },
  { nome: "Venosa", provincia: "PZ" },
  { nome: "Lagonegro", provincia: "PZ" },
  { nome: "Senise", provincia: "PZ" },
  // RA - Ravenna
  { nome: "Ravenna", provincia: "RA" },
  { nome: "Faenza", provincia: "RA" },
  { nome: "Lugo", provincia: "RA" },
  { nome: "Cervia", provincia: "RA" },
  // RC - Reggio Calabria
  { nome: "Reggio Calabria", provincia: "RC" },
  { nome: "Gioia Tauro", provincia: "RC" },
  { nome: "Palmi", provincia: "RC" },
  { nome: "Locri", provincia: "RC" },
  // RE - Reggio Emilia
  { nome: "Reggio Emilia", provincia: "RE" },
  { nome: "Scandiano", provincia: "RE" },
  { nome: "Guastalla", provincia: "RE" },
  { nome: "Correggio", provincia: "RE" },
  // RG - Ragusa
  { nome: "Ragusa", provincia: "RG" },
  { nome: "Modica", provincia: "RG" },
  { nome: "Vittoria", provincia: "RG" },
  { nome: "Comiso", provincia: "RG" },
  // RI - Rieti
  { nome: "Rieti", provincia: "RI" },
  { nome: "Amatrice", provincia: "RI" },
  { nome: "Magliano Sabina", provincia: "RI" },
  { nome: "Poggio Mirteto", provincia: "RI" },
  // RM - Roma
  { nome: "Roma", provincia: "RM" },
  { nome: "Fiumicino", provincia: "RM" },
  { nome: "Guidonia Montecelio", provincia: "RM" },
  { nome: "Tivoli", provincia: "RM" },
  { nome: "Velletri", provincia: "RM" },
  { nome: "Civitavecchia", provincia: "RM" },
  { nome: "Frascati", provincia: "RM" },
  // RN - Rimini
  { nome: "Rimini", provincia: "RN" },
  { nome: "Riccione", provincia: "RN" },
  { nome: "Cattolica", provincia: "RN" },
  { nome: "Santarcangelo di Romagna", provincia: "RN" },
  // RO - Rovigo
  { nome: "Rovigo", provincia: "RO" },
  { nome: "Adria", provincia: "RO" },
  { nome: "Porto Tolle", provincia: "RO" },
  // SA - Salerno
  { nome: "Salerno", provincia: "SA" },
  { nome: "Ravello", provincia: "SA" },
  { nome: "Amalfi", provincia: "SA" },
  { nome: "Vallo della Lucania", provincia: "SA" },
  { nome: "Agropoli", provincia: "SA" },
  { nome: "Eboli", provincia: "SA" },
  { nome: "Paestum", provincia: "SA" },
  { nome: "Battipaglia", provincia: "SA" },
  { nome: "Positano", provincia: "SA" },
  { nome: "Pontecagnano Faiano", provincia: "SA" },
  { nome: "Cava de' Tirreni", provincia: "SA" },
  // SI - Siena
  { nome: "Siena", provincia: "SI" },
  { nome: "Montepulciano", provincia: "SI" },
  { nome: "Montalcino", provincia: "SI" },
  { nome: "San Gimignano", provincia: "SI" },
  { nome: "Pienza", provincia: "SI" },
  { nome: "Radda in Chianti", provincia: "SI" },
  { nome: "Buonconvento", provincia: "SI" },
  { nome: "Chianciano Terme", provincia: "SI" },
  { nome: "Castiglione d'Orcia", provincia: "SI" },
  { nome: "Colle di Val d'Elsa", provincia: "SI" },
  { nome: "Poggibonsi", provincia: "SI" },
  { nome: "Castellina in Chianti", provincia: "SI" },
  { nome: "Gaiole in Chianti", provincia: "SI" },
  { nome: "Piancastagnaio", provincia: "SI" },
  { nome: "Trequanda", provincia: "SI" },
  { nome: "Murlo", provincia: "SI" },
  // SO - Sondrio
  { nome: "Sondrio", provincia: "SO" },
  { nome: "Morbegno", provincia: "SO" },
  { nome: "Livigno", provincia: "SO" },
  { nome: "Bormio", provincia: "SO" },
  // SP - La Spezia
  { nome: "La Spezia", provincia: "SP" },
  { nome: "Sarzana", provincia: "SP" },
  { nome: "Lerici", provincia: "SP" },
  { nome: "Portovenere", provincia: "SP" },
  // SR - Siracusa
  { nome: "Siracusa", provincia: "SR" },
  { nome: "Augusta", provincia: "SR" },
  { nome: "Noto", provincia: "SR" },
  { nome: "Avola", provincia: "SR" },
  { nome: "Pachino", provincia: "SR" },
  // SS - Sassari
  { nome: "Sassari", provincia: "SS" },
  { nome: "Porto Torres", provincia: "SS" },
  { nome: "Alghero", provincia: "SS" },
  { nome: "Sorso", provincia: "SS" },
  // SU - Sud Sardegna
  { nome: "Carbonia", provincia: "SU" },
  { nome: "Iglesias", provincia: "SU" },
  { nome: "Villacidro", provincia: "SU" },
  { nome: "Guspini", provincia: "SU" },
  // SV - Savona
  { nome: "Savona", provincia: "SV" },
  { nome: "Albenga", provincia: "SV" },
  { nome: "Finale Ligure", provincia: "SV" },
  { nome: "Cairo Montenotte", provincia: "SV" },
  // TA - Taranto
  { nome: "Taranto", provincia: "TA" },
  { nome: "Massafra", provincia: "TA" },
  { nome: "Manduria", provincia: "TA" },
  { nome: "Grottaglie", provincia: "TA" },
  // TE - Teramo
  { nome: "Teramo", provincia: "TE" },
  { nome: "Roseto degli Abruzzi", provincia: "TE" },
  { nome: "Giulianova", provincia: "TE" },
  { nome: "Alba Adriatica", provincia: "TE" },
  // TN - Trento
  { nome: "Trento", provincia: "TN" },
  { nome: "Rovereto", provincia: "TN" },
  { nome: "Riva del Garda", provincia: "TN" },
  { nome: "Arco", provincia: "TN" },
  { nome: "Pergine Valsugana", provincia: "TN" },
  // TO - Torino
  { nome: "Torino", provincia: "TO" },
  { nome: "Moncalieri", provincia: "TO" },
  { nome: "Rivoli", provincia: "TO" },
  { nome: "Nichelino", provincia: "TO" },
  { nome: "Collegno", provincia: "TO" },
  // TP - Trapani
  { nome: "Trapani", provincia: "TP" },
  { nome: "Marsala", provincia: "TP" },
  { nome: "Mazara del Vallo", provincia: "TP" },
  { nome: "Castelvetrano", provincia: "TP" },
  // TR - Terni
  { nome: "Terni", provincia: "TR" },
  { nome: "Orvieto", provincia: "TR" },
  { nome: "Narni", provincia: "TR" },
  { nome: "Amelia", provincia: "TR" },
  { nome: "Montefalco", provincia: "TR" },
  { nome: "Acquasparta", provincia: "TR" },
  { nome: "Gualdo Cattaneo", provincia: "TR" },
  // TS - Trieste
  { nome: "Trieste", provincia: "TS" },
  { nome: "Muggia", provincia: "TS" },
  // TV - Treviso
  { nome: "Treviso", provincia: "TV" },
  { nome: "Conegliano", provincia: "TV" },
  { nome: "Vittorio Veneto", provincia: "TV" },
  { nome: "Montebelluna", provincia: "TV" },
  { nome: "Castelfranco Veneto", provincia: "TV" },
  // UD - Udine
  { nome: "Udine", provincia: "UD" },
  { nome: "Pordenone", provincia: "UD" },
  { nome: "Cividale del Friuli", provincia: "UD" },
  { nome: "Palmanova", provincia: "UD" },
  // VA - Varese
  { nome: "Varese", provincia: "VA" },
  { nome: "Busto Arsizio", provincia: "VA" },
  { nome: "Gallarate", provincia: "VA" },
  { nome: "Saronno", provincia: "VA" },
  // VB - Verbano-Cusio-Ossola
  { nome: "Verbania", provincia: "VB" },
  { nome: "Omegna", provincia: "VB" },
  { nome: "Domodossola", provincia: "VB" },
  // VC - Vercelli
  { nome: "Vercelli", provincia: "VC" },
  { nome: "Borgosesia", provincia: "VC" },
  { nome: "Santhià", provincia: "VC" },
  // VE - Venezia
  { nome: "Venezia", provincia: "VE" },
  { nome: "Mestre", provincia: "VE" },
  { nome: "Chioggia", provincia: "VE" },
  { nome: "San Donà di Piave", provincia: "VE" },
  { nome: "Jesolo", provincia: "VE" },
  // VI - Vicenza
  { nome: "Vicenza", provincia: "VI" },
  { nome: "Bassano del Grappa", provincia: "VI" },
  { nome: "Schio", provincia: "VI" },
  { nome: "Thiene", provincia: "VI" },
  { nome: "Valdagno", provincia: "VI" },
  // VR - Verona
  { nome: "Verona", provincia: "VR" },
  { nome: "Villafranca di Verona", provincia: "VR" },
  { nome: "Legnago", provincia: "VR" },
  { nome: "San Bonifacio", provincia: "VR" },
  { nome: "Bardolino", provincia: "VR" },
  // VT - Viterbo
  { nome: "Viterbo", provincia: "VT" },
  { nome: "Civita di Bagnoregio", provincia: "VT" },
  { nome: "Bolsena", provincia: "VT" },
  { nome: "Tuscania", provincia: "VT" },
  { nome: "Montefiascone", provincia: "VT" },
  { nome: "Caprarola", provincia: "VT" },
  { nome: "Tarquinia", provincia: "VT" },
  { nome: "Sutri", provincia: "VT" },
  { nome: "Ronciglione", provincia: "VT" },
  // VV - Vibo Valentia
  { nome: "Vibo Valentia", provincia: "VV" },
  { nome: "Tropea", provincia: "VV" },
  { nome: "Pizzo", provincia: "VV" },
];

export function getComuniByProvincia(codice: string): string[] {
  return COMUNI.filter((c) => c.provincia === codice)
    .map((c) => c.nome)
    .sort();
}
